- name: Deploy your app to GitHub Pages
  uses: awibox/deploy-to-github-pages-action@1.1.1

name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.19.0]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Deploy to production
        uses: devnirajc/niraj-portfolio@master
        env:
          AUTHOR: Niraj Chavan
          BUILD_PATH: public
          GITHUB_PAGE_NAME: niraj-chavan.github.io
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: devnirajc
          EMAIL: nirajd327@gmail.com